### ISSUE TITLE
Fails to create zip if parent folder does on exist

### ISSUE THREAD

**Issue by jordanbtucker** [Malcomian/zipadeedoodah#1]
After running the following command and receiving this output:

```
zipadeedoodah -o dist/test -g test/** -l 9
  ____  _              __           __             __     __ 
 /_  / (_)__  ___ ____/ /__ ___ ___/ /__  ___  ___/ /__ _/ / 
  / /_/ / _ \/ _ `/ _  / -_) -_) _  / _ \/ _ \/ _  / _ `/ _ \
 /___/_/ .__/\_,_/\_,_/\__/\__/\_,_/\___/\___/\_,_/\_,_/_//_/
      /_/

version 1.0.8
Archiving [...]\dist\test.zip at compression level 9...
Archived 1 file and 1 directory
Wrote 228B in 1987ms
```

`dist/test.zip` does not exist because `dist` does not exist despite zipadeedoodah saying it succeeded.

Running `mkdir dist` before the command does create `dist/test.zip`.

- Node.js v16.13.2
- zipadeedoodah v1.0.8
- Windows 10

**Comment by Malcomian** [comment]
Oh hey, looks like I didn't have a case for when the output folder doesn't exist. Thanks for catching that.

I added some code to throw an error message and exit if the output folder doesn't exist.

**Comment by jordanbtucker** [comment]
Thanks. While this does handle this one edge case, what you really want is an error handler on the `output` steam.

When you `pipe` streams, the error handlers do not get passed down.

```js
var output = fs.createWriteStream(path)

output.on('error', err => {
  // This will only catch errors emitted by `output`.
})

archive.pipe(output).on('error', err => {
  // This will also only catch errors emitted by `output`
  // since `pipe` returns the destination stream.
})

archive.on('error', err => {
  // This will only catch errors emitted by `archive`.
})
```

Couple this with the facts that archiver does not forward errors and the stream created by `createWriteStream` will happily accept any write operations even though it didn't really create a stream and you can see why no error was being thrown.

Adding an error handler to the `output` stream will catch any other stream errors that might come up, including when the parent folder doesn't exist.

**Comment by Malcomian** [comment]
Sure thing, and thanks again for your input.

I'll just add the following, although I must admit that I don't know a lot about these sorts of error messages.

```javascript
output.on('error', (error) => {
  throw error
}
```

This whole project was really just a quick and easy way for me to make a cross platform zip archiver, so it's just based on the basic examples on archiver's npm page. Seems they didn't handle the error event on the `output` stream on their front page in the docs, either.

**Comment by jordanbtucker** [comment]
> although I must admit that I don't know a lot about these sorts of error messages.

That's okay. It's better to throw and let the user figure out what the internal error message means than to fail silently.

> Seems they didn't handle the error event on the output stream on their front page in the docs, either.

I noticed that too. Maybe I should open an issue with archiver.

Two other minor things I noticed:

You don't return a [non-zero exit code](https://github.com/Malcomian/zipadeedoodah/blob/ea8c58c0edf7dfcf118ee5fe1280fd575a8ad230/index.js#L154) when invalid arguments are provided, which means running `zipadeedoodah && some-other-command` will cause `some-other-command` to run when it shouldn't.

You check for the existence of `-p` or `-c` in the arg list, but this could give false positives if the user's value for an argument is `-p` or `-c`. (e.g. `zipadeedoodah -o -p -g dist/** -l 9` creates a file named `-p.zip` as intended, but it will also prompt the user for a comment when it shouldn't. `zipadeedoodah -o -c -g dist/** -l 9 -p` creates a file named `-c.zip` as intended, but it will not prompt the user for a comment even though `-p` was specified.) This is, of course, a very rare edge case.

**Comment by Malcomian** [comment]
> I noticed that too. Maybe I should open an issue with archiver.

I mean, why not? Seems like an important thing to handle, even in an example.

> You don't return a [non-zero exit code](https://github.com/Malcomian/zipadeedoodah/blob/ea8c58c0edf7dfcf118ee5fe1280fd575a8ad230/index.js#L154) when invalid arguments are provided, which means running zipadeedoodah && some-other-command will cause some-other-command to run when it shouldn't.

Yeah, I didn't exit with a code because I legit didn't know what those were at the time, let alone what they were for. Evidently that double ampersand chains commands together, too - I see it sometimes but wasn't sure exactly what the behavior was.

> You check for the existence of -p or -c in the arg list, but this could give false positives

I get that I'm not at all parsing args correctly here - I bet I could run another instance of Commander or something lighter like yargs-parser just to make sure there's a proper prompt for a comment and no given comment already. Actually, the latter seems like the right thing to do.

The idea was that the script would be able to run either with or without a prompt depending on which arguments are present. Usually I just type `npx zipadeedoodah` and mash the enter key to make a snapshot of the folder I'm working in, but I also enjoy using it as an npm package script with other ignore patterns. Like having a `zip-clean` or a `zip-all` command around.

I could always just use something like tar or 7zip instead, but I thought it'd be fun to make a cross platform sort of command line interface.

Thanks again for your help. I actually use this package so it seems like something worth getting right.

**Comment by jordanbtucker** [comment]
> Evidently that double ampersand chains commands together, too - I see it sometimes but wasn't sure exactly what the behavior was.

Yep. This also works for tools like `npm-run-all`, which will chain together multiple npm scripts. Say you had the following npm scripts:

```json
{
  "zip": "zipadeedoodah -o dist -g dist/** -l 9",
  "upload": "./scripts/upload.sh dist.zip",
  "publish": "run-s zip upload"
}
```

The `publish` script calls `run-s` which is a binary in the `npm-run-all` package that runs each script listed as args and stops at the first one that fails. This is roughly equivalent to `&&`. Without the non-zero exit code, `run-s` would run the `upload` script even if the `zip` script failed. There's also a `-c` flag that will run all scripts regardless of error codes, and some shells allow you to use a single `&` in that way too.
